### PR TITLE
Implement Adapter

### PR DESCRIPTION
**Pull request by critiqjo**
- [x] Spec tests
- [ ] Footnote support

### CODE REVIEW

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by kagura-chan** [comment]
:hourglass: Trying commit 401ac37 with merge 5824a4b...

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by kagura-chan** [comment]
:hourglass: Trying commit b4f444f with merge f9ab200...

**Comment by kagura-chan** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/critiqjo/cmark-hamlet/builds/126880108)

**Comment by kagura-chan** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/critiqjo/cmark-hamlet/builds/126880108)

**Comment by critiqjo** [comment]
@kagura-chan try

**Comment by kagura-chan** [comment]
:hourglass: Trying commit 1929619 with merge 4bc3094...

**Comment by kagura-chan** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/critiqjo/cmark-hamlet/builds/126881008)

**Comment by kagura-chan** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/critiqjo/cmark-hamlet/builds/126881008)

**Comment by nixpulvis** [comment]
Out of curiosity how is one supposed to build this? I currently get:

```
can't find crate for `rustc_front`
```

Which makes sense considering all I did was clone this repo. It would be nice for the compiler crates to be hosted and detectable by cargo wouldn't it?

**Pull request merged**
